import type { MetricObservation } from "./financial-types.ts";

// Append observations. Corrections reference superseded IDs; never rewrite historical values.
export const financialObservations: MetricObservation[] = [
  {
    "id": "polsia-annual_run_rate-import-2026-09-12",
    "slug": "polsia",
    "kind": "annual_run_rate",
    "value": null,
    "currency": "USD",
    "precision": "unknown",
    "display": "~$10M",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "reported",
    "source": {
      "name": "Pulse2 · self-reported",
      "url": "https://pulse2.com/polsia-30-million-at-250-million-valuation-raised-for-ai-operations-platform/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "polsia-headcount-import-2026-09-12",
    "slug": "polsia",
    "kind": "headcount",
    "value": 1,
    "currency": null,
    "precision": "unknown",
    "display": "1",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Pulse2",
      "url": "https://pulse2.com/polsia-30-million-at-250-million-valuation-raised-for-ai-operations-platform/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "nanocorp-arr-import-2026-09-12",
    "slug": "nanocorp",
    "kind": "arr",
    "value": 193000,
    "currency": "USD",
    "precision": "exact",
    "display": "$193K (claimed)",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "disputed",
    "source": {
      "name": "Founder claim · disputed",
      "url": "https://www.alexisbouchez.com/reviews/2026/03/30/nanocorp"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "nanocorp-headcount-import-2026-09-12",
    "slug": "nanocorp",
    "kind": "headcount",
    "value": 1,
    "currency": null,
    "precision": "unknown",
    "display": "1",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Y Combinator",
      "url": "https://www.ycombinator.com/companies/nanocorp"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "chainopera-ai-headcount-import-2026-09-12",
    "slug": "chainopera-ai",
    "kind": "headcount",
    "value": 40,
    "currency": null,
    "precision": "lower_bound",
    "display": "40+ reported team",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "The Block ('40+ team')",
      "url": "https://www.theblock.co/post/332347/chainopera-ai-raised-17-million-in-seed-funding-to-build-blockchain-l1-and-ai-os-for-ai-agents"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "wordware-headcount-import-2026-09-12",
    "slug": "wordware",
    "kind": "headcount",
    "value": 15,
    "currency": null,
    "precision": "unknown",
    "display": "15",
    "asOf": "2024-11",
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Forbes (at Nov 2024 raise)",
      "url": "https://www.forbes.com/sites/dariashunina/2024/11/27/how-wordware-secured-30m-seed-in-7-days/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "semio-headcount-import-2026-09-12",
    "slug": "semio",
    "kind": "headcount",
    "value": 7,
    "currency": null,
    "precision": "unknown",
    "display": "7",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Tracxn",
      "url": "https://tracxn.com/d/companies/semio/__BjN5hbn1zB_pkpRlyXAAgGbYOUmuxV496mQpEjKqmfA"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "base44-unclassified-import-2026-09-12",
    "slug": "base44",
    "kind": "unclassified",
    "value": null,
    "currency": "USD",
    "precision": "unknown",
    "display": "$3.5M at exit → $150M under Wix",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "unclassified",
    "source": {
      "name": "Getlatka / Wix earnings",
      "url": "https://getlatka.com/blog/base44-revenue-acquired-wix/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Legacy entry combines pre-acquisition and post-acquisition figures; split observations supersede it."
  },
  {
    "id": "base44-headcount-import-2026-09-12",
    "slug": "base44",
    "kind": "headcount",
    "value": 9,
    "currency": null,
    "precision": "unknown",
    "display": "9",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "TechCrunch (1 founder + 8 staff)",
      "url": "https://techcrunch.com/2025/06/18/6-month-old-solo-owned-vibe-coder-base44-sells-to-wix-for-80m-cash/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "midjourney-unclassified-import-2026-09-12",
    "slug": "midjourney",
    "kind": "unclassified",
    "value": 500000000,
    "currency": "USD",
    "precision": "approximate",
    "display": "~$500M",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "estimated",
    "source": {
      "name": "Third-party estimates",
      "url": "https://sacra.com/c/midjourney/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "midjourney-headcount-import-2026-09-12",
    "slug": "midjourney",
    "kind": "headcount",
    "value": 60,
    "currency": null,
    "precision": "unknown",
    "display": "60",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Getlatka (~60; others up to 190)",
      "url": "https://getlatka.com/companies/midjourney"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "artisan-unclassified-import-2026-09-12",
    "slug": "artisan",
    "kind": "unclassified",
    "value": 5000000,
    "currency": "USD",
    "precision": "lower_bound",
    "display": "$5M+",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "reported",
    "source": {
      "name": "TechCrunch",
      "url": "https://techcrunch.com/2025/04/09/artisan-the-stop-hiring-humans-ai-agent-startup-raises-25m-and-is-still-hiring-humans/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "artisan-headcount-import-2026-09-12",
    "slug": "artisan",
    "kind": "headcount",
    "value": 35,
    "currency": null,
    "precision": "unknown",
    "display": "35",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Getlatka",
      "url": "https://getlatka.com/companies/artisan.co"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "lindy-unclassified-import-2026-09-12",
    "slug": "lindy",
    "kind": "unclassified",
    "value": 5100000,
    "currency": "USD",
    "precision": "approximate",
    "display": "$5.1M (2024 est.)",
    "asOf": "2024",
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "estimated",
    "source": {
      "name": "Getlatka (2024 est.)",
      "url": "https://getlatka.com/companies/lindyai"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "lindy-headcount-import-2026-09-12",
    "slug": "lindy",
    "kind": "headcount",
    "value": 52,
    "currency": null,
    "precision": "unknown",
    "display": "52",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Tracxn",
      "url": "https://tracxn.com/d/companies/lindy/__FJe0QVe6UcRHtdiPJpmyRG3livSd4eIGsIxMxz-kNPI"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "basis-headcount-import-2026-09-12",
    "slug": "basis",
    "kind": "headcount",
    "value": 76,
    "currency": null,
    "precision": "unknown",
    "display": "76",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Getlatka",
      "url": "https://getlatka.com/companies/getbasis.ai"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "delphi-headcount-import-2026-09-12",
    "slug": "delphi",
    "kind": "headcount",
    "value": 37,
    "currency": null,
    "precision": "unknown",
    "display": "37",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Tracxn",
      "url": "https://tracxn.com/d/companies/delphi/__sanFr2u2e2tuCcA8J4CoLaZ1mPK11wUadGeq5Xb_Ois"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "payman-unclassified-import-2026-09-12",
    "slug": "payman",
    "kind": "unclassified",
    "value": 770000,
    "currency": "USD",
    "precision": "approximate",
    "display": "$770K (2025 est.)",
    "asOf": "2025",
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "estimated",
    "source": {
      "name": "Getlatka (2025 est.)",
      "url": "https://getlatka.com/companies/paymanai.com"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "payman-headcount-import-2026-09-12",
    "slug": "payman",
    "kind": "headcount",
    "value": 15,
    "currency": null,
    "precision": "unknown",
    "display": "15",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Tracxn",
      "url": "https://tracxn.com/d/companies/paymanai/__NSTYOZtZdNiGZxC0Vkul0dzUfj3ZUgPqDRNO08pHBUE"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "rentahuman-annual_run_rate-import-2026-09-12",
    "slug": "rentahuman",
    "kind": "annual_run_rate",
    "value": 240000,
    "currency": "USD",
    "precision": "approximate",
    "display": "~$240K run rate (claimed $20K MRR)",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "reported",
    "source": {
      "name": "YC profile · self-reported",
      "url": "https://www.ycombinator.com/companies/rentahuman"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "rentahuman-headcount-import-2026-09-12",
    "slug": "rentahuman",
    "kind": "headcount",
    "value": 3,
    "currency": null,
    "precision": "unknown",
    "display": "3",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Y Combinator",
      "url": "https://www.ycombinator.com/companies/rentahuman"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "naive-annual_run_rate-import-2026-09-12",
    "slug": "naive",
    "kind": "annual_run_rate",
    "value": null,
    "currency": "USD",
    "precision": "range",
    "display": "Low double-digit $M run-rate (self-reported)",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "reported",
    "source": {
      "name": "SiliconANGLE · self-reported",
      "url": "https://siliconangle.com/2026/08/06/naive-bags-28-5m-funding-automate-creation-day-day-running-almost-business/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "moritz-headcount-import-2026-09-12",
    "slug": "moritz",
    "kind": "headcount",
    "value": 10,
    "currency": null,
    "precision": "unknown",
    "display": "10",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Y Combinator",
      "url": "https://www.ycombinator.com/companies/moritz"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "minimal-ai-unclassified-import-2026-09-12",
    "slug": "minimal-ai",
    "kind": "unclassified",
    "value": null,
    "currency": "USD",
    "precision": "range",
    "display": "7-figure (self-reported)",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "reported",
    "source": {
      "name": "Founder-stated · self-reported",
      "url": "https://www.ycombinator.com/companies/minimal-ai"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "minimal-ai-headcount-import-2026-09-12",
    "slug": "minimal-ai",
    "kind": "headcount",
    "value": 3,
    "currency": null,
    "precision": "unknown",
    "display": "3",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Y Combinator",
      "url": "https://www.ycombinator.com/companies/minimal-ai"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "lunavo-headcount-import-2026-09-12",
    "slug": "lunavo",
    "kind": "headcount",
    "value": 2,
    "currency": null,
    "precision": "unknown",
    "display": "2",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Y Combinator",
      "url": "https://www.ycombinator.com/companies/lunavo"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "beacon-health-headcount-import-2026-09-12",
    "slug": "beacon-health",
    "kind": "headcount",
    "value": 2,
    "currency": null,
    "precision": "unknown",
    "display": "2",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Y Combinator",
      "url": "https://www.ycombinator.com/companies/beacon-health"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "gamma-arr-import-2026-09-12",
    "slug": "gamma",
    "kind": "arr",
    "value": 100000000,
    "currency": "USD",
    "precision": "approximate",
    "display": "$100M (Nov 2025)",
    "asOf": "2025-11",
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "reported",
    "source": {
      "name": "TechCrunch",
      "url": "https://techcrunch.com/2025/11/10/ai-powerpoint-killer-gamma-hits-2-1b-valuation-100m-arr-founder-says/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "gamma-headcount-import-2026-09-12",
    "slug": "gamma",
    "kind": "headcount",
    "value": 52,
    "currency": null,
    "precision": "unknown",
    "display": "52",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Lean AI Leaderboard / Sacra",
      "url": "https://sacra.com/c/gamma/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "retell-ai-annual_run_rate-import-2026-09-12",
    "slug": "retell-ai",
    "kind": "annual_run_rate",
    "value": 60000000,
    "currency": "USD",
    "precision": "approximate",
    "display": "~$60M annualized (Sacra est., Apr 2026)",
    "asOf": "2026-04",
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "estimated",
    "source": {
      "name": "Sacra · estimate",
      "url": "https://sacra.com/research/retell-ai-60m-yr-up-650-yoy/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "retell-ai-headcount-import-2026-09-12",
    "slug": "retell-ai",
    "kind": "headcount",
    "value": null,
    "currency": null,
    "precision": "unknown",
    "display": "Disputed headcount",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "disputed",
    "source": {
      "name": "Disputed: 21 (leaderboard) → 143 (Tracxn)",
      "url": "https://leanaileaderboard.com/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "11x-unclassified-import-2026-09-12",
    "slug": "11x",
    "kind": "unclassified",
    "value": null,
    "currency": "USD",
    "precision": "unknown",
    "display": "claimed $10M; disputed ~$3M",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": null,
    "status": "disputed",
    "source": {
      "name": "TechCrunch investigation",
      "url": "https://techcrunch.com/2025/03/24/a16z-and-benchmark-backed-11x-has-been-claiming-customers-it-doesnt-have/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "11x-headcount-import-2026-09-12",
    "slug": "11x",
    "kind": "headcount",
    "value": 77,
    "currency": null,
    "precision": "unknown",
    "display": "77",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "Tracxn",
      "url": "https://tracxn.com/d/companies/11x/__P4mFd4dOZmyEt3qkI243p5AtNH1AhqMZw4A4Zd1scY4"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "egbe-headcount-import-2026-09-12",
    "slug": "egbe",
    "kind": "headcount",
    "value": 5,
    "currency": null,
    "precision": "unknown",
    "display": "5",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "LinkedIn · self-reported",
      "url": "https://www.linkedin.com/company/egbe-ai/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "medvi-revenue-import-2026-09-12",
    "slug": "medvi",
    "kind": "revenue",
    "value": 401000000,
    "currency": "USD",
    "precision": "approximate",
    "display": "$401M sales in 2025",
    "asOf": "2025-12-31",
    "periodStart": "2025-01-01",
    "periodEnd": "2025-12-31",
    "scope": "medvi",
    "population": null,
    "status": "reported",
    "source": {
      "name": "NYT (financials reviewed)",
      "url": "https://www.nytimes.com/2026/04/02/technology/ai-billion-dollar-company-medvi.html"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "medvi-revenue_projection-import-2026-09-12",
    "slug": "medvi",
    "kind": "revenue_projection",
    "value": 1800000000,
    "currency": "USD",
    "precision": "approximate",
    "display": "$1.8B projected 2026 sales",
    "asOf": "2026",
    "periodStart": "2026-01-01",
    "periodEnd": "2026-12-31",
    "scope": "medvi",
    "population": null,
    "status": "reported",
    "source": {
      "name": "NYT (financials reviewed)",
      "url": "https://www.nytimes.com/2026/04/02/technology/ai-billion-dollar-company-medvi.html"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Separated from 2025 sales. Historical projection, not realized revenue; source not rechecked during import."
  },
  {
    "id": "medvi-headcount-import-2026-09-12",
    "slug": "medvi",
    "kind": "headcount",
    "value": 2,
    "currency": null,
    "precision": "unknown",
    "display": "2",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": null,
    "population": "team_unspecified",
    "status": "unclassified",
    "source": {
      "name": "NYT (financials reviewed)",
      "url": "https://www.nytimes.com/2026/04/02/technology/ai-billion-dollar-company-medvi.html"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "medvi-contractors-import-2026-09-12",
    "slug": "medvi",
    "kind": "contractors",
    "value": 9,
    "currency": null,
    "precision": "unknown",
    "display": "9",
    "asOf": null,
    "periodStart": null,
    "periodEnd": null,
    "scope": "medvi",
    "population": "contractors",
    "status": "reported",
    "source": {
      "name": "NYT (financials reviewed)",
      "url": "https://www.nytimes.com/2026/04/02/technology/ai-billion-dollar-company-medvi.html"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": null,
    "supersedes": null,
    "notes": "Imported from the existing research record; source not rechecked during import. Missing dates remain unknown."
  },
  {
    "id": "gamma-arr-review-2026-09-12",
    "slug": "gamma",
    "kind": "arr",
    "value": 100000000,
    "currency": "USD",
    "precision": "lower_bound",
    "display": "More than $100M ARR",
    "asOf": "2025-11-10",
    "periodStart": null,
    "periodEnd": null,
    "scope": "gamma",
    "population": null,
    "status": "reported",
    "source": {
      "name": "Gamma founder announcement",
      "url": "https://gamma.app/insights/how-we-built-a-usd100m-business-differently"
    },
    "publishedAt": "2025-11-10",
    "recordedAt": "2026-09-12",
    "checkedAt": "2026-09-12",
    "supersedes": "gamma-arr-import-2026-09-12",
    "notes": "Dated source reviewed; this is not an independent financial audit or a current operating measurement."
  },
  {
    "id": "gamma-headcount-review-2026-09-12",
    "slug": "gamma",
    "kind": "headcount",
    "value": 50,
    "currency": null,
    "precision": "approximate",
    "display": "50 employees (founder announcement)",
    "asOf": "2025-11-10",
    "periodStart": null,
    "periodEnd": null,
    "scope": "gamma",
    "population": "employees",
    "status": "reported",
    "source": {
      "name": "Gamma founder announcement",
      "url": "https://gamma.app/insights/how-we-built-a-usd100m-business-differently"
    },
    "publishedAt": "2025-11-10",
    "recordedAt": "2026-09-12",
    "checkedAt": "2026-09-12",
    "supersedes": "gamma-headcount-import-2026-09-12",
    "notes": "The first-party announcement says 50 employees; the legacy secondary record said 52 humans. Population and precision differ; this is not proof of a headcount reduction."
  },
  {
    "id": "base44-arr-2025-06-review",
    "slug": "base44",
    "kind": "arr",
    "value": 3500000,
    "currency": "USD",
    "precision": "approximate",
    "display": "~$3.5M ARR at acquisition (unconfirmed estimate)",
    "asOf": "2025-06",
    "periodStart": null,
    "periodEnd": null,
    "scope": "base44-pre-acquisition",
    "population": null,
    "status": "estimated",
    "source": {
      "name": "GetLatka correction: unofficial estimate",
      "url": "https://getlatka.com/blog/base44-revenue-acquired-wix/"
    },
    "publishedAt": null,
    "recordedAt": "2026-09-12",
    "checkedAt": "2026-09-12",
    "supersedes": "base44-unclassified-import-2026-09-12",
    "notes": "Source correction says this figure was never confirmed by Wix or the founder and traces to a Reddit thread. Excluded from numeric ranking."
  },
  {
    "id": "base44-arr-review-2026-09-12",
    "slug": "base44",
    "kind": "arr",
    "value": 150000000,
    "currency": "USD",
    "precision": "approximate",
    "display": "~$150M ARR under Wix",
    "asOf": "2026-05",
    "periodStart": null,
    "periodEnd": null,
    "scope": "base44-under-wix",
    "population": null,
    "status": "reported",
    "source": {
      "name": "Wix Q1 2026 results",
      "url": "https://www.wix.com/press-room/home/post/wix-reports-first-quarter-2026-results"
    },
    "publishedAt": "2026-05-13",
    "recordedAt": "2026-09-12",
    "checkedAt": "2026-09-12",
    "supersedes": null,
    "notes": "Dated source reviewed; this is not an independent financial audit or a current operating measurement."
  },
  {
    "id": "base44-headcount-review-2026-09-12",
    "slug": "base44",
    "kind": "headcount",
    "value": 9,
    "currency": null,
    "precision": "exact",
    "display": "1 founder + 8 employees",
    "asOf": "2025-06-18",
    "periodStart": null,
    "periodEnd": null,
    "scope": "base44-pre-acquisition",
    "population": "employees_and_founders",
    "status": "reported",
    "source": {
      "name": "TechCrunch (1 founder + 8 staff)",
      "url": "https://techcrunch.com/2025/06/18/6-month-old-solo-owned-vibe-coder-base44-sells-to-wix-for-80m-cash/"
    },
    "publishedAt": "2025-06-18",
    "recordedAt": "2026-09-12",
    "checkedAt": "2026-09-12",
    "supersedes": "base44-headcount-import-2026-09-12",
    "notes": "Historical pre-acquisition team. No compatible post-acquisition headcount is recorded."
  },
  {
    "id": "polsia-annual_run_rate-review-2026-09-12",
    "slug": "polsia",
    "kind": "annual_run_rate",
    "value": null,
    "currency": "USD",
    "precision": "unknown",
    "display": "Approaching $10M annual run rate",
    "asOf": "2026-05",
    "periodStart": null,
    "periodEnd": null,
    "scope": "polsia",
    "population": null,
    "status": "reported",
    "source": {
      "name": "Pulse2 · self-reported",
      "url": "https://pulse2.com/polsia-30-million-at-250-million-valuation-raised-for-ai-operations-platform/"
    },
    "publishedAt": "2026-05-25",
    "recordedAt": "2026-09-12",
    "checkedAt": "2026-09-12",
    "supersedes": "polsia-annual_run_rate-import-2026-09-12",
    "notes": "Founder claim reported by Pulse2. Approaching a milestone is not an exact amount; not ARR and excluded from numeric ranking."
  },
  {
    "id": "polsia-headcount-review-2026-09-12",
    "slug": "polsia",
    "kind": "headcount",
    "value": 1,
    "currency": null,
    "precision": "exact",
    "display": "1 founder; zero employees reported",
    "asOf": "2026-05",
    "periodStart": null,
    "periodEnd": null,
    "scope": "polsia",
    "population": "employees_and_founders",
    "status": "reported",
    "source": {
      "name": "Pulse2 · self-reported",
      "url": "https://pulse2.com/polsia-30-million-at-250-million-valuation-raised-for-ai-operations-platform/"
    },
    "publishedAt": "2026-05-25",
    "recordedAt": "2026-09-12",
    "checkedAt": "2026-09-12",
    "supersedes": "polsia-headcount-import-2026-09-12",
    "notes": "Dated source reviewed; this is not an independent financial audit or a current operating measurement."
  }
];
